/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdiantamentoRouteImport } from './routes/adiantamento'
import { Route as IndexRouteImport } from './routes/index'

const AdiantamentoRoute = AdiantamentoRouteImport.update({
  id: '/adiantamento',
  path: '/adiantamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adiantamento': typeof AdiantamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adiantamento': typeof AdiantamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adiantamento': typeof AdiantamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adiantamento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adiantamento'
  id: '__root__' | '/' | '/adiantamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdiantamentoRoute: typeof AdiantamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/adiantamento': {
      id: '/adiantamento'
      path: '/adiantamento'
      fullPath: '/adiantamento'
      preLoaderRoute: typeof AdiantamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdiantamentoRoute: AdiantamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
